my_string = input('Мои хобби: ')
print('Количество символов:', len(my_string))
print('Заглавные:',my_string.upper())
print('Строчные:', my_string.lower())
print('Пробелы удалены:', my_string.replace(' ', ''))
print('Первый символ строки: ', my_string[0])
print('Последний символ сроки: ', my_string[-1])